In [14]:
from datascience import *
import numpy as np


## Words of Caution ##
- Remember to run the cell above. It's for setting up the environment so you can have access to what's needed for this lecture. For now, don't worry about what it means: we'll learn more about what's inside of it in the next few lectures.
- Data science is not just about code, so please don't go over this notebook by itself. Have the relevant textbook sections or lecture video at hand so that you can go over the discussion along with the code. Thank you! 

## Python ##

In [15]:
2 + 9

11

In [16]:
2 * 9

18

In [17]:
2 / 9

0.2222222222222222

In [18]:
2 + 3 * 9

29

In [19]:
(2 + 3) * 9

45

In [20]:
# two to the power of four: 2 * 2 * 2 * 2
2 ** 4

16

In [21]:
'hello'

'hello'

In [22]:
"Hello in 'Busan'"

"Hello in 'Busan'"

## Names ##

In [23]:
a = 4

In [24]:
a

4

In [25]:
b = 9

In [26]:
b

9

In [27]:
a * 3

12

In [28]:
total = a + b # a 는 여전히 4

In [29]:
total

13

In [30]:
a = 10

In [31]:
total

13

In [32]:
total = a + b

In [33]:
total

19

In [34]:
'total'

'total'

### Why Names? 

변수에 대한 설명

In [35]:
# Option 1
40 * 14.00

560.0

In [36]:
40 * 52 * 14.00

29120.0

In [37]:
# Option 2
ca_hourly_minimum_wage = 14.00
hours_per_week = 40
weeks_per_year = 52

In [38]:
hours_per_year = hours_per_week * weeks_per_year

In [39]:
hours_per_year

2080

In [40]:
weekly_wages = hours_per_week * ca_hourly_minimum_wage
weekly_wages

560.0

In [41]:
yearly_wages = hours_per_year * ca_hourly_minimum_wage
yearly_wages

29120.0

## Functions and Call Expressions

In [42]:
abs(-5)

5

In [43]:
abs(1 - 3)

2

In [44]:
day_temp = 52
night_temp = 47
abs(night_temp - day_temp)

5

In [45]:
min(14, 15)

14

In [46]:
round(123.456)

123

In [47]:
round(123.456, 1)

123.5

In [48]:
round(123.456, ndigits=1)

123.5

In [49]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



## Scientific notation 
=> 1.0*10^500 = 1.0e+500

In [54]:
round?

In [55]:
int('12')

12

In [56]:
x = 3
y = '4'
z = '5.6'

In [57]:
x+y

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [58]:
x+int((y)+(z))

ValueError: invalid literal for int() with base 10: '45.6'

In [59]:
str(x)+int(y) # string은 오직 string과만 concatenate(이어붙이기)가 가능하다.

TypeError: can only concatenate str (not "int") to str

In [60]:
y+float(z)

TypeError: can only concatenate str (not "float") to str

In [61]:
type(2)

int

In [62]:
type(2+2)

int

In [63]:
type(2.5) 

float

In [64]:
english_pars_of_sppech = make_array("noun","pronoun","verb","adverb","adjective","conjunction","preposition","interjunction")
english_pars_of_sppech

array(['noun', 'pronoun', 'verb', 'adverb', 'adjective', 'conjunction',
       'preposition', 'interjunction'],
      dtype='<U13')

In [65]:
a = [1,2,3,4] # list 생성해서 a에 할당

In [66]:
np.array(a) + 2 # 이미 생성된 리스트를 array로 변환후 각각의 값에다 2 더함s

array([3, 4, 5, 6])

In [67]:
baseline_high = 14.48


In [68]:
highs = make_array([baseline_high - 0.880, baseline_high - 0.093,
baseline_high + 0.105, baseline_high + 0.684])

In [69]:
highs

array([[13.6, 14.387, 14.585, 15.164]], dtype=object)

In [70]:
my_array = make_array([0,1,2,3,4,5])
my_array2= make_array([5,4,3,2,1,0])
my_array+my_array2

array([[5, 5, 5, 5, 5, 5]], dtype=object)

In [71]:
my_np_arr = np.array([5,4,3,2])

In [72]:
baseline_low = 3.00


In [73]:
lows = np.array([baseline_low - 0.872, baseline_low - 0.629,
baseline_low - 0.126, baseline_low + 0.728]) 

In [74]:
lows

array([ 2.128,  2.371,  2.874,  3.728])

In [75]:
zero_arr = np.array([1,0,0,0])
zero_arr.all()

False

In [76]:
np.count_nonzero(zero_arr)

1

In [77]:
np.all(lows)

True

In [78]:
np.any(lows)

True

In [79]:
np.arange(0,4) # [start, end)

array([0, 1, 2, 3])

In [80]:
np.arange(-1,2.5,0.5)

array([-1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ])

In [81]:
highs-lows # np.array([highs.item(0)-lows.item(0) ... ])

array([[11.472, 12.016, 11.711, 11.436]], dtype=object)

In [82]:
by_four_to_20 = np.arange(1,20,4)
by_four_to_20

array([ 1,  5,  9, 13, 17])

In [83]:
positive_term_denominators = np.arange(1,10000,4)
positive_term_denominators

array([   1,    5,    9, ..., 9989, 9993, 9997])

In [95]:
positive_term = 1 / positive_term_denominators
positive_term

array([  1.00000000e+00,   2.00000000e-01,   1.11111111e-01, ...,
         1.00110121e-04,   1.00070049e-04,   1.00030009e-04])

In [96]:
negative_term = 1 / (positive_term_denominators+2)
negative_term

array([  3.33333333e-01,   1.42857143e-01,   9.09090909e-02, ...,
         1.00090081e-04,   1.00050025e-04,   1.00010001e-04])

In [97]:
4 * (sum(positive_term) - sum(negative_term))

3.1413926535917955

## Tables ##

In [98]:
cones = Table.read_table('./documents/cones.csv')
cones

Flavor     | Color       | Price | Rating
strawberry | pink        | 3.55  | 1
chocolate  | light brown | 4.75  | 4
chocolate  | dark brown  | 5.25  | 3
strawberry | pink        | 5.25  | 2
chocolate  | dark brown  | 5.25  | 5
bubblegum  | pink        | 4.75  | 1

In [99]:
cones.show(3) # 3개의 row만 출력 

In [89]:
cones.show() #출력

In [90]:
cones.select('Flavor') # flavor attrivute(Categroail attribute, Nomial attribute)

Flavor
strawberry
chocolate
chocolate
strawberry
chocolate
bubblegum

In [91]:
cones.select('Flavor', 'Price') 

Flavor     | Price
strawberry | 3.55
chocolate  | 4.75
chocolate  | 5.25
strawberry | 5.25
chocolate  | 5.25
bubblegum  | 4.75

In [92]:
cones.drop('Price') # drop the price attribute

Flavor     | Color       | Rating
strawberry | pink        | 1
chocolate  | light brown | 4
chocolate  | dark brown  | 3
strawberry | pink        | 2
chocolate  | dark brown  | 5
bubblegum  | pink        | 1

In [93]:
cones # 다만 cones 변수에 재할당하지 않았으므로 cones는 그대로이다.

Flavor     | Color       | Price | Rating
strawberry | pink        | 3.55  | 1
chocolate  | light brown | 4.75  | 4
chocolate  | dark brown  | 5.25  | 3
strawberry | pink        | 5.25  | 2
chocolate  | dark brown  | 5.25  | 5
bubblegum  | pink        | 4.75  | 1

In [94]:
cones_without_price = cones.drop('Price') # 
cones_without_price

Flavor     | Color       | Rating
strawberry | pink        | 1
chocolate  | light brown | 4
chocolate  | dark brown  | 3
strawberry | pink        | 2
chocolate  | dark brown  | 5
bubblegum  | pink        | 1

In [122]:
cones.where('Flavor', 'chocolate') # flavor attrbute의 value가 chocolate인 row들만 출력 # SELECT * FROM CONES WHERE "Flavor" == "chocolate"

Flavor    | Color       | Price | Rating
chocolate | light brown | 4.75  | 4
chocolate | dark brown  | 5.25  | 3
chocolate | dark brown  | 5.25  | 5

In [123]:
cones.sort('Price')

Flavor     | Color       | Price | Rating
strawberry | pink        | 3.55  | 1
chocolate  | light brown | 4.75  | 4
bubblegum  | pink        | 4.75  | 1
chocolate  | dark brown  | 5.25  | 3
strawberry | pink        | 5.25  | 2
chocolate  | dark brown  | 5.25  | 5

In [124]:
cones.sort('Price', descending=True) # descending = False 가 defautl 오름차순을 의미

Flavor     | Color       | Price | Rating
chocolate  | dark brown  | 5.25  | 3
strawberry | pink        | 5.25  | 2
chocolate  | dark brown  | 5.25  | 5
chocolate  | light brown | 4.75  | 4
bubblegum  | pink        | 4.75  | 1
strawberry | pink        | 3.55  | 1

In [125]:
cones.sort('Flavor', descending=True)

Flavor     | Color       | Price | Rating
strawberry | pink        | 3.55  | 1
strawberry | pink        | 5.25  | 2
chocolate  | light brown | 4.75  | 4
chocolate  | dark brown  | 5.25  | 3
chocolate  | dark brown  | 5.25  | 5
bubblegum  | pink        | 4.75  | 1

### A more interesting table

In [130]:
Table.read_table('./documents/nba_salaries.csv')

rank | name             | position | team                   | salary   | season
1    | Shaquille O'Neal | C        | Los Angeles Lakers     | 17142000 | 2000
2    | Kevin Garnett    | PF       | Minnesota Timberwolves | 16806000 | 2000
3    | Alonzo Mourning  | C        | Miami Heat             | 15004000 | 2000
4    | Juwan Howard     | PF       | Washington Wizards     | 15000000 | 2000
5    | Scottie Pippen   | SF       | Portland Trail Blazers | 14795000 | 2000
6    | Karl Malone      | PF       | Utah Jazz              | 14000000 | 2000
7    | Larry Johnson    | F        | New York Knicks        | 11910000 | 2000
8    | Gary Payton      | PG       | Seattle SuperSonics    | 11020000 | 2000
9    | Rasheed Wallace  | PF       | Portland Trail Blazers | 10800000 | 2000
10   | Shawn Kemp       | C        | Cleveland Cavaliers    | 10780000 | 2000
... (9446 rows omitted)

In [139]:
nba = Table.read_table('./documents/nba_salaries.csv').relabeled(3, 'SALARY')
# 원래 3번 레이블(0부터 시작)을 'SALARY'로 바꿈
nba

rank | name             | position | SALARY                 | salary   | season
1    | Shaquille O'Neal | C        | Los Angeles Lakers     | 17142000 | 2000
2    | Kevin Garnett    | PF       | Minnesota Timberwolves | 16806000 | 2000
3    | Alonzo Mourning  | C        | Miami Heat             | 15004000 | 2000
4    | Juwan Howard     | PF       | Washington Wizards     | 15000000 | 2000
5    | Scottie Pippen   | SF       | Portland Trail Blazers | 14795000 | 2000
6    | Karl Malone      | PF       | Utah Jazz              | 14000000 | 2000
7    | Larry Johnson    | F        | New York Knicks        | 11910000 | 2000
8    | Gary Payton      | PG       | Seattle SuperSonics    | 11020000 | 2000
9    | Rasheed Wallace  | PF       | Portland Trail Blazers | 10800000 | 2000
10   | Shawn Kemp       | C        | Cleveland Cavaliers    | 10780000 | 2000
... (9446 rows omitted)

In [140]:
point_guards = nba.where('position', 'PG')
# position인 PG인 것만 추출 #PG: point guard

In [141]:
point_guards

rank | name             | position | SALARY                 | salary   | season
8    | Gary Payton      | PG       | Seattle SuperSonics    | 11020000 | 2000
11   | Damon Stoudamire | PG       | Portland Trail Blazers | 10125000 | 2000
20   | Stephon Marbury  | PG       | New Jersey Nets        | 9000000  | 2000
24   | Nick Van Exel    | PG       | Denver Nuggets         | 8354000  | 2000
26   | Terrell Brandon  | PG       | Minnesota Timberwolves | 7400000  | 2000
34   | Jason Kidd       | PG       | Phoenix Suns           | 6858000  | 2000
35   | Kenny Anderson   | PG       | Boston Celtics         | 6680000  | 2000
39   | Steve Nash       | PG       | Dallas Mavericks       | 5500000  | 2000
55   | Charlie Ward     | PG       | New York Knicks        | 4540000  | 2000
61   | Darrel Armstrong | PG       | Orlando Magic          | 4125000  | 2000
... (1465 rows omitted)

In [142]:
point_guards.drop('position')
# position 열 삭제

rank | name             | SALARY                 | salary   | season
8    | Gary Payton      | Seattle SuperSonics    | 11020000 | 2000
11   | Damon Stoudamire | Portland Trail Blazers | 10125000 | 2000
20   | Stephon Marbury  | New Jersey Nets        | 9000000  | 2000
24   | Nick Van Exel    | Denver Nuggets         | 8354000  | 2000
26   | Terrell Brandon  | Minnesota Timberwolves | 7400000  | 2000
34   | Jason Kidd       | Phoenix Suns           | 6858000  | 2000
35   | Kenny Anderson   | Boston Celtics         | 6680000  | 2000
39   | Steve Nash       | Dallas Mavericks       | 5500000  | 2000
55   | Charlie Ward     | New York Knicks        | 4540000  | 2000
61   | Darrel Armstrong | Orlando Magic          | 4125000  | 2000
... (1465 rows omitted)

In [143]:
point_guards

rank | name             | position | SALARY                 | salary   | season
8    | Gary Payton      | PG       | Seattle SuperSonics    | 11020000 | 2000
11   | Damon Stoudamire | PG       | Portland Trail Blazers | 10125000 | 2000
20   | Stephon Marbury  | PG       | New Jersey Nets        | 9000000  | 2000
24   | Nick Van Exel    | PG       | Denver Nuggets         | 8354000  | 2000
26   | Terrell Brandon  | PG       | Minnesota Timberwolves | 7400000  | 2000
34   | Jason Kidd       | PG       | Phoenix Suns           | 6858000  | 2000
35   | Kenny Anderson   | PG       | Boston Celtics         | 6680000  | 2000
39   | Steve Nash       | PG       | Dallas Mavericks       | 5500000  | 2000
55   | Charlie Ward     | PG       | New York Knicks        | 4540000  | 2000
61   | Darrel Armstrong | PG       | Orlando Magic          | 4125000  | 2000
... (1465 rows omitted)

In [144]:
point_guards = point_guards.drop('position')

In [155]:
point_guards.sort('salary', descending=True).show()
# salary 열을 기준으로 내림차순 정렬 # 고액연봉자부터 출력된다.

In [151]:
point_guards.sort('salary', descending=True).show(15)

In [147]:
nba.where('position')

rank | name             | position | SALARY                 | salary   | season
1    | Shaquille O'Neal | C        | Los Angeles Lakers     | 17142000 | 2000
2    | Kevin Garnett    | PF       | Minnesota Timberwolves | 16806000 | 2000
3    | Alonzo Mourning  | C        | Miami Heat             | 15004000 | 2000
4    | Juwan Howard     | PF       | Washington Wizards     | 15000000 | 2000
5    | Scottie Pippen   | SF       | Portland Trail Blazers | 14795000 | 2000
6    | Karl Malone      | PF       | Utah Jazz              | 14000000 | 2000
7    | Larry Johnson    | F        | New York Knicks        | 11910000 | 2000
8    | Gary Payton      | PG       | Seattle SuperSonics    | 11020000 | 2000
9    | Rasheed Wallace  | PF       | Portland Trail Blazers | 10800000 | 2000
10   | Shawn Kemp       | C        | Cleveland Cavaliers    | 10780000 | 2000
... (9446 rows omitted)

In [153]:
nba.where('position', 'PG').drop('position')

rank | name             | SALARY                 | salary   | season
8    | Gary Payton      | Seattle SuperSonics    | 11020000 | 2000
11   | Damon Stoudamire | Portland Trail Blazers | 10125000 | 2000
20   | Stephon Marbury  | New Jersey Nets        | 9000000  | 2000
24   | Nick Van Exel    | Denver Nuggets         | 8354000  | 2000
26   | Terrell Brandon  | Minnesota Timberwolves | 7400000  | 2000
34   | Jason Kidd       | Phoenix Suns           | 6858000  | 2000
35   | Kenny Anderson   | Boston Celtics         | 6680000  | 2000
39   | Steve Nash       | Dallas Mavericks       | 5500000  | 2000
55   | Charlie Ward     | New York Knicks        | 4540000  | 2000
61   | Darrel Armstrong | Orlando Magic          | 4125000  | 2000
... (1465 rows omitted)