In [73]:
from datascience import *
import numpy as np


## Words of Caution ##
- Remember to run the cell above. It's for setting up the environment so you can have access to what's needed for this lecture. For now, don't worry about what it means: we'll learn more about what's inside of it in the next few lectures.
- Data science is not just about code, so please don't go over this notebook by itself. Have the relevant textbook sections or lecture video at hand so that you can go over the discussion along with the code. Thank you! 

## Python ##

In [2]:
2 + 9

11

In [3]:
2 * 9

18

In [4]:
2 / 9

0.2222222222222222

In [5]:
2 + 3 * 9

29

In [6]:
(2 + 3) * 9

45

In [7]:
# two to the power of four: 2 * 2 * 2 * 2
2 ** 4

16

In [8]:
'hello'

'hello'

In [9]:
"Hello in 'Busan'"

"Hello in 'Busan'"

## Names ##

In [10]:
a = 4

In [11]:
a

4

In [12]:
b = 9

In [13]:
b

9

In [14]:
a * 3

12

In [15]:
total = a + b # a 는 여전히 4

In [16]:
total

13

In [17]:
a = 10

In [18]:
total

13

In [19]:
total = a + b

In [20]:
total

19

In [21]:
'total'

'total'

### Why Names? 

변수에 대한 설명

In [22]:
# Option 1
40 * 14.00

560.0

In [23]:
40 * 52 * 14.00

29120.0

In [24]:
# Option 2
ca_hourly_minimum_wage = 14.00
hours_per_week = 40
weeks_per_year = 52

In [25]:
hours_per_year = hours_per_week * weeks_per_year

In [26]:
hours_per_year

2080

In [27]:
weekly_wages = hours_per_week * ca_hourly_minimum_wage
weekly_wages

560.0

In [28]:
yearly_wages = hours_per_year * ca_hourly_minimum_wage
yearly_wages

29120.0

## Functions and Call Expressions

In [29]:
abs(-5)

5

In [30]:
abs(1 - 3)

2

In [31]:
day_temp = 52
night_temp = 47
abs(night_temp - day_temp)

5

In [32]:
min(14, 15)

14

In [33]:
round(123.456)

123

In [34]:
round(123.456, 1)

123.5

In [35]:
round(123.456, ndigits=1)

123.5

In [36]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.


## Scientific notation 
=> 1.0*10^500 = 1.0e+500

In [37]:
round?

In [39]:
int('12')

12

In [41]:
x = 3
y = '4'
z = '5.6'

In [49]:
x+y

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [59]:
x+int((y)+(z))

ValueError: invalid literal for int() with base 10: '45.6'

In [58]:
str(x)+int(y) # string은 오직 string과만 concatenate(이어붙이기)가 가능하다.

TypeError: can only concatenate str (not "int") to str

In [46]:
y+float(z)

TypeError: can only concatenate str (not "float") to str

In [63]:
type(2)

int

In [65]:
type(2+2)

int

In [67]:
type(2.5) 

float

In [69]:
english_pars_of_sppech = make_array("noun","pronoun","verb","adverb","adjective","conjunction","preposition","interjunction")
english_pars_of_sppech

array(['noun', 'pronoun', 'verb', 'adverb', 'adjective', 'conjunction',
       'preposition', 'interjunction'],
      dtype='<U13')

In [70]:
a = [1,2,3,4]

In [79]:
np.array(a) + 2 # 이미 생성된 리스트를 array로 변환후 각각의 값에다 2 더함s

array([3, 4, 5, 6])

In [90]:
baseline_high = 14.48


In [101]:
highs = make_array([baseline_high - 0.880, baseline_high - 0.093,
baseline_high + 0.105, baseline_high + 0.684])

In [106]:
highs

array([[13.6, 14.387, 14.585, 15.164]], dtype=object)

In [86]:
baseline_low = 3.00


In [100]:
lows = np.array([baseline_low - 0.872, baseline_low - 0.629,
baseline_low - 0.126, baseline_low + 0.728]) 

In [107]:
lows

array([ 2.128,  2.371,  2.874,  3.728])

In [110]:
np.all(lows)

True

In [111]:
np.any(lows)

True

In [118]:
np.arange(0,4) # [start, end)

array([0, 1, 2, 3])

In [119]:
np.arange(-1,2.5,0.5)

array([-1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ])

In [98]:
highs-lows # np.array([highs.item(0)-lows.item(0) ... ])

array([[11.472, 12.016, 11.711, 11.436]], dtype=object)

In [120]:
by_four_to_20 = np.arange(1,20,4)
by_four_to_20

array([ 1,  5,  9, 13, 17])

In [121]:
positive_term_denominators = np.arange(1,10000,4)
positive_term_denominators

array([   1,    5,    9, ..., 9989, 9993, 9997])

In [122]:
positive_term = 1 / positive_term_denominators

In [123]:
negative_term = 1 / (positive_term_denominators+2)

In [124]:
4 * (sum(positive_term) - sum(negative_term))

3.1413926535917955

## Tables ##

In [ ]:
cones = Table.read_table('cones.csv')
cones

In [ ]:
cones.show(3)

In [ ]:
cones.show()

In [ ]:
cones.select('Flavor')

In [ ]:
cones.select('Flavor', 'Price')

In [ ]:
cones.drop('Price')

In [ ]:
cones

In [ ]:
cones_without_price = cones.drop('Price')
cones_without_price

In [ ]:
cones.where('Flavor', 'chocolate')

In [ ]:
cones.sort('Price')

In [ ]:
cones.sort('Price', descending=True)

In [ ]:
cones.sort('Flavor', descending=True)

### A more interesting table

In [ ]:
Table.read_table('nba_salaries.csv')

In [ ]:
nba = Table.read_table('nba_salaries.csv').relabeled(3, 'SALARY')
nba

In [ ]:
point_guards = nba.where('position', 'PG')

In [ ]:
point_guards

In [ ]:
point_guards.drop('position')

In [ ]:
point_guards

In [ ]:
point_guards = point_guards.drop('position')

In [ ]:
point_guards.sort('SALARY', descending=True).show()

In [ ]:
point_guards.sort('salary', descending=True).show(15)

In [ ]:
nba.where('position')

In [ ]:
nba.drop('position').where('position', 'PG')